### PR TITLE
Add interpolation

### PR DESCRIPTION
**Pull request by tr11**
This PR adds the feature suggested in #18.

### CODE REVIEW

**Comment by chinghwayu** [comment]
This is _really_ close! There's a use case I didn't outline where it's failing.

```python
a = {"var1": "This {var2} {var3}", "var2": "is a {var3}", "var3": "test"}
print(a["var1"].format(**a).format(**a))
cfg = config(a, interpolate=True)
print(cfg["var1"])
```
The first output is
```this is a test test```

but the branch returns:
```ValueError: Cycle detected while interpolating keys```

**Comment by tr11** [comment]
That makes sense. The assumption was one interpolation per value, but I see that fails in your case.  Let me just change that check for cycles and this should be good.

**Comment by tr11** [comment]
Your example should pass with the last commit.

**Comment by chinghwayu** [comment]
> Your example should pass with the last commit.

yup, also working with my real world configuration sets. thanks for the quick work!

**Comment by chinghwayu** [comment]
Actually, I encountered another use case which is interpolation in iterables. Example:
```
>>> a = {"var1": ["This {var2} {var3}"], "var2": "is a {var3}", "var3": "test"}
>>>a["var1"]
['This is a test']
```
and even nested iterables...
```
>>>a = {"var1": [["This", "{var2} {var3}"]], "var2": "is a {var3}", "var3": "test"}
>>>a["var1"]
[['This', 'is a test']]
```

**Comment by tr11** [comment]
@chinghwayu, can you confirm if the last commit does what you need?

**Comment by chinghwayu** [comment]
I’m currently away from my dev system but I did quickly try it out
yesterday and it didn’t fully work. I didn’t get a chance to fully debug
but I think has to do with interpolating across configuration sets. Does
the functionality support this?

The use case is to have a master configuration template and then in a lower
level of a hierarchy, set values to those variables for interpolation. This
would include strings and iterables.

**Comment by tr11** [comment]
Yeah, totally overlooked adding this to Configuration Sets.  The last commit takes care of that.

**Comment by chinghwayu** [comment]
> Yeah, totally overlooked adding this to Configuration Sets. The last commit takes care of that.

Checked the test case where it was failing and it's now working. I'm going to check other cases tomorrow...

**Comment by chinghwayu** [comment]
I've checked the most complex layered configuration and that seems to working!

**Pull request merged**
